version: '3'

services:
  php:
    build:
      context: src  # Direktori yang berisi Dockerfile
    networks:
      - internal
  proxy:
    image: nginx:latest
    restart: always
    ports:
      - 8086:80
    volumes:
      - ./src:/var/www/html:rw
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal
    depends_on:
      - php
      - bot
  bot:
    build:
      context: bot
      args:
        - BROWSER=chromium
    restart: always
    environment:
      APPNAME: Admin
      APPURL: http://proxy/
      APPURLREGEX: ^http(|s)://.*$$
      APPFLAG: AVC{3cbf792b-0cce-4e0e-889f-7f3b7ab8da28}
      APPLIMIT: 2
      APPLIMITTIME: 60
      USE_PROXY: 1
      DISPLAY: ${DISPLAY}
    networks:
      - internal
    # uncoment this if you need to run the bot in GUI mode
    # run this before running the docker container if you're use xauth `sudo xhost +local:docker`
    # volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix

networks:
  internal:
